# Generated by Django 3.2.15 on 2024-07-14 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('last_message', models.CharField(max_length=10000)),
                ('last_date', models.IntegerField()),
                ('last_writer', models.CharField(max_length=100)),
                ('last_message_statut', models.CharField(default='sent', max_length=100)),
                ('creation_date', models.IntegerField(default=1720923533)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telephone1', models.CharField(max_length=200)),
                ('telephone2', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='CAMEROUN', max_length=200)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('type', models.CharField(default='garage', max_length=200)),
                ('creation_date', models.IntegerField(default=1720923533)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(max_length=100)),
                ('garage', models.CharField(max_length=100)),
                ('rate', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=100)),
                ('creation_date', models.IntegerField(default=1720923533)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('access', models.CharField(default='', max_length=300)),
                ('refresh', models.CharField(default='', max_length=300)),
                ('ip', models.CharField(default='', max_length=1000)),
                ('end_time', models.IntegerField(default=1723515533)),
                ('creation_date', models.IntegerField(default=1720923533)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('creation_date', models.IntegerField(default=1720923533)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('photo', models.CharField(default='', max_length=200)),
                ('sexe', models.CharField(max_length=100)),
                ('date_naissance', models.IntegerField(default=0)),
                ('type', models.CharField(default='user', max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('pays', models.CharField(default='CAMEROUN', max_length=200)),
                ('creation_date', models.IntegerField(default=1720923533)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('contenu', models.CharField(max_length=10000)),
                ('media', models.CharField(default='none', max_length=200)),
                ('answerTo', models.CharField(default='none', max_length=200)),
                ('date_envoi', models.IntegerField(default=1720923533)),
                ('creation_date', models.IntegerField(default=1720923533)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muntur.discussion')),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muntur.user')),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.AddField(
            model_name='discussion',
            name='initiateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emeteur', to='muntur.user'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='interlocuteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='interlocuteur', to='muntur.user'),
        ),
    ]
