# Generated by Django 3.2.15 on 2024-09-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muntur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='heure_fermeture',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='garage',
            name='heure_ouverture',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='creation_date',
            field=models.IntegerField(default=1726423834),
        ),
        migrations.AlterField(
            model_name='garage',
            name='creation_date',
            field=models.IntegerField(default=1726423834),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.IntegerField(default=1726423834),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_envoi',
            field=models.IntegerField(default=1726423834),
        ),
        migrations.AlterField(
            model_name='rate',
            name='creation_date',
            field=models.IntegerField(default=1726423834),
        ),
        migrations.AlterField(
            model_name='session',
            name='creation_date',
            field=models.IntegerField(default=1726423834),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.IntegerField(default=1729015834),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.IntegerField(default=1726423834),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.IntegerField(default=1726423834),
        ),
    ]
