# Generated by Django 3.2.15 on 2024-09-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muntur', '0002_auto_20240915_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='creation_date',
            field=models.IntegerField(default=1726427274),
        ),
        migrations.AlterField(
            model_name='garage',
            name='creation_date',
            field=models.IntegerField(default=1726427274),
        ),
        migrations.AlterField(
            model_name='garage',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.IntegerField(default=1726427274),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_envoi',
            field=models.IntegerField(default=1726427274),
        ),
        migrations.AlterField(
            model_name='rate',
            name='creation_date',
            field=models.IntegerField(default=1726427274),
        ),
        migrations.AlterField(
            model_name='session',
            name='creation_date',
            field=models.IntegerField(default=1726427274),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.IntegerField(default=1729019274),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.IntegerField(default=1726427274),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.IntegerField(default=1726427274),
        ),
    ]
